version: '3.4'

services:
  deeplearning:
    image: deeplearning
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
     - .:/app
    ports:
      - 8088:8080
      - 8888:8888
